#!/usr/bin/env python
#!coding=utf-8

import os
import sys
import cv2
import numpy as np
import fnmatch

def cropBorder(img):

    im = cv2.imread(img)
    height, width, pose = im.shape
    imgCrop = im[0:(height-120), 0:width]
    cv2.imwrite(img, imgCrop)
    cv2.destroyAllWindows()

def checkRaio(img):

    im = cv2.imread(img)
    height, width = im.shape[:2]
    cv2.destroyAllWindows()

    ratio = 1.0*width/height
    ratio = "%.1f" % ratio

    if height > 1080:
        cropBorder(img)

def reshapeRatio(img):

    imgBlack = np.zeros((1080, 1920, 3), np.uint8)  # height(row), width(col)
    im = cv2.imread(img)
    height, width, pose = im.shape

    imgBlack[0:height, 0:width] = im    # x1:x2 y1:y2

    imgName = os.path.basename(img)
    cv2.imwrite("new1/" + imgName, imgBlack)
    cv2.destroyAllWindows()

def gen_find(filepat="*", top=None):
    '''
    Find all filenames in a directory tree that match a shell wildcard pattern
    '''
    for path, dirlist, filelist in os.walk(top):
        for name in fnmatch.filter(filelist, filepat):
            yield os.path.join(path,name)

def run(pathName):

    fileNames = gen_find(filepat="*.jpg", top=pathName)
    for fileName in fileNames:
        checkRaio(fileName)
        reshapeRatio(fileName)
   
if __name__ == '__main__':
    top='1'
    run(top) 
